# Spotyfy Status
[module/previous]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 0.3
; Previous song icon
exec = echo ""
; Check if spotify is running before displaying the icon
exec-if = "pgrep spotify -x"
format-underline = #1db954
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"

[module/next]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 0.3
; Next song icon
exec = echo ""
; Check if spotify is running before displaying the icon
exec-if = "pgrep spotify -x"
format-underline = #1db954
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"

[module/playpause]
type = custom/ipc
; Default
hook-0 = echo ""
; Playing
hook-1 = echo ""
; Paused
hook-2 = echo ""
initial = 1
format-underline = #1db954
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"


[module/spotify]
type = custom/script
interval = 1
format-prefix = " "
format = <label>
format-prefix-foreground = #1db954
exec = python ~/dotfiles/scripts/spotify_status.py  -t 42 -f '{artist}: {song}'
format-underline = #1db954

# Spotyfy Status - version 2

[module/spotify2]
type = custom/script
tail = true
interval = 1
; prefix symbol is shown before the text
format-prefix = " "
format-prefix-foreground = #1db954
format-underline = #1db954
format = <label>
exec = ~/dotfiles/scripts/scroll_spotify_status.sh
exec-if = "playerctl -a status 2>/dev/null"

[module/spotify2-prev]
type = custom/script
exec = echo ""
format = <label>
format-prefix-foreground = #1db954
format-underline = #1db954
click-left = playerctl previous -p spotify
exec-if = "pgrep spotify -x"

[module/spotify2-play-pause]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo ""
initial = 1
click-left = playerctl play-pause -p spotify
format-prefix-foreground = #1db954
format-underline = #1db954
exec-if = "pgrep spotify -x"

[module/spotify2-next]
type = custom/script
exec = echo ""
format = <label>
format-prefix-foreground = #1db954
format-underline = #1db954
click-left = playerctl next -p spotify
exec-if = "pgrep spotify -x"