# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[ ](bold blue)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
# [character]
# success_symbol = "[ ](blue)"
# # success_symbol = "[➜](bold green) "
# error_symbol = "[✗](bold red) "

format = """
$hostname $git_branch$git_commit$git_state$git_status
[§ ](blue)$directory$cmd_duration$battery[§](blue) """
# [<](blue)$directory$cmd_duration$battery[/>](blue) """
# $directory$cmd_duration$battery[ ](blue) """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# format ="""
# $all
# [ ](blue) """


# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[hostname]
ssh_only = true
format = "[@$hostname](bold cyan)"


# GIT

[git_branch]
# symbol = "🌱 "
# symbol = ""
truncation_length = 6
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
# tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
# conflicted = "🏳"
# ahead = "🔥 " # git push
# behind = "😰 " #
# diverged = "😵 " #
# untracked = "🤷 ‍" # Something
# stashed = "📦 "
# modified = "📝 "
staged = '[++\($count\)](green)'
# renamed = "👅 "
# deleted = "🗑 "

# Battery
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# [directory]
# truncation_length = 8
# truncation_symbol = "~../"
