[bar/example]
inherit = bar/template
monitor = ${env:eDP-1}

modules-left = Herbstluftwm spotify2
modules-center = date phrase
modules-right = mic pulseaudio battery memory cpu temperature
;powermenu
