include-file = ~/.config/polybar/modules/common.ini
include-file = ~/.config/polybar/modules/audio.ini
include-file = ~/.config/polybar/modules/bspwm.ini
include-file = ~/.config/polybar/modules/herbstluftwm.ini
include-file = ~/.config/polybar/modules/i3.ini
include-file = ~/.config/polybar/modules/menus.ini
include-file = ~/.config/polybar/modules/my-controll-mic-baterry.ini
include-file = ~/.config/polybar/modules/phrase.ini
include-file = ~/.config/polybar/modules/spotify.ini

include-file = ~/.config/polybar/bar/template.ini
include-file = ~/.config/polybar/bar/example.ini

[colors]
;background = ${xrdb:color0:#222}

; com cena preta (azul)
;background = #222
;background-alt = #bf444
;foreground = #FFFFFF
;#dfdfdf
;foreground-alt = #555
;primary = #009999
;#ffb52a
;secondary = #50ffff
;#e60053
;alert = #bd2c40
;;ilike = #15dae8

; transparency blue
;background = #00000000
;background-alt = #bf444
;foreground = #FFFFFF
;foreground-alt = #555
;primary = #045761
;#ffb52a
;secondary = #50ffff
;#e60053
;alert = #bd2c40
;;ilike = #15dae8


; transparency preta
background = #00000000
background-alt = #bf444
foreground = #FFFFFF
foreground-alt = #555
primary = #ffffff
secondary = #50ffff
alert = #bd2c40

#######################
#        Modules      #
######################

[global/wm]
margin-top = 5
margin-bottom = 5

#######################
#       BARS      #
######################
[bar/MONITOR-HDMI-1]
inherit = bar/template
monitor = ${env:MONITOR:HDMI-1}

modules-left = Herbstluftwm
;bspwm i3
modules-center = date spotify2
modules-right = mic pulseaudio memory cpu temperature

[bar/MONITOR-HDMI-2]
inherit = bar/template
monitor = ${env:MONITOR:HDMI-2}

modules-left = Herbstluftwm
;bspwm i3
modules-center = date spotify2
modules-right = mic pulseaudio memory cpu temperature

[bar/MONITOR-DP-1]
inherit = bar/template
monitor = ${env:MONITOR:DP-1}

modules-left = Herbstluftwm bspwm i3
modules-center = date spotify2
modules-right = mic pulseaudio memory cpu temperature

[bar/MONITOR-DP-2]
inherit = bar/template
monitor = ${env:MONITOR:DP-2}

modules-left = Herbstluftwm bspwm i3
modules-center = date spotify2
modules-right = mic pulseaudio memory cpu temperature

[bar/MONITOR-DP-3]
inherit = bar/template
monitor = ${env:MONITOR:DP-3}

modules-left = Herbstluftwm bspwm i3
modules-center = date spotify2
modules-right = mic pulseaudio memory cpu temperature

